name: Go

on:
  push:
  #   branches: [ $default-branch ]
  # pull_request:
  #   branches: [ $default-branch ]

jobs:
  generate-stubs:
    runs-on: ubuntu-latest
    steps:
      - name: generating stubs
        run: echo "generating stubs"
      - name: run
        run: |
            go env -w GOPRIVATE=github.com/devminnu/protobufs && \
            go env -w GO111MODULE=on && \
            sudo apt install -y protobuf-compiler && \
            go get google.golang.org/protobuf/cmd/protoc-gen-go@v1.26 && \
            go get google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1 && \
            export PATH="$PATH:$(go env GOPATH)/bin"
      - name: gensss
        run: |      
            protoc --go_out=. --go-grpc_out=. \
            --go_opt=paths=import  \
            --govalidators_out=. \
            --go-grpc_opt=paths=import .
