name: Go

on:
  push:
  #   branches: [ $default-branch ]
  # pull_request:
  #   branches: [ $default-branch ]

jobs:
  generate-stubs:
    runs-on: ubuntu-latest
    steps:
      - name: echo generating stubs
        run: echo "generating stubs"
      - name: run
        run: |
            sudo apt install -y protobuf-compiler && \
            go install google.golang.org/protobuf/cmd/protoc-gen-go && \
            go install google.golang.org/grpc/cmd/protoc-gen-go-grpc && \
            export PATH="$PATH:$(go env GOPATH)/bin" && \
            protoc --go_out=. --go-grpc_out=. \
            --go_opt=paths=import  \
            --govalidators_out=. \
            --go-grpc_opt=paths=import ./...
