# name: Go

# on:
#   push:
#   #   branches: [ $default-branch ]
#   # pull_request:
#   #   branches: [ $default-branch ]

# jobs:
#   generate-stubs:
#     runs-on: ubuntu-latest
#     steps:
#       - name: uses
#         uses: "devminnu/protobufs@main"
#         with:
#           test: test
#       - name: gensss
#         run: protoc -I=. --go_out=. ./...


name: reviewdog
on: [push]
jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
          exclude: |
            "*.js"
