name: Go

on:
  push:
  #   branches: [ $default-branch ]
  # pull_request:
  #   branches: [ $default-branch ]

jobs:
  generate-stubs:
    runs-on: ubuntu-latest
    steps:
      - name: uses
        uses: "github.com/devminnu/protobufs"
        with:
          test: test
      - name: gensss
        run: protoc -I=. --go_out=. ./...

