name: Go

on:
  push:
  #   branches: [ $default-branch ]
  # pull_request:
  #   branches: [ $default-branch ]

jobs:
  generate-stubs:
    runs-on: ubuntu-latest
    steps:
      - name: echo generating stubs
        run: echo "generating stubs"
      - name: run
        run: |
            apt install -y protobuf-compiler && \
            protoc --go_out=. --go-grpc_out=. \
            --go_opt=paths=import  \
            --govalidators_out=. \
            --go-grpc_opt=paths=import ecommerce/*/*
